### ISSUE TITLE
Update Releases

### ISSUE THREAD

**Issue by cjsfj** [luisiam/homebridge-liftmaster2#11]
Would it be possible to add a release to GitHub with every version?

Seems like it's on 0.3.0 now, but because of the way NPM works a release is needed to bump the version from 0.1.0 on downstream systems.

If not, I am happy using the full GitHub URL to install.. just thought it might simplify things.

Thanks for putting this together.

CJ

**Comment by luisiam** [comment]
Someone hijacked the npm release. If you noticed, adair21 published that in npm and I have no control over that. I can publish the plugin with a new name but I can't think of any good name now.

**Comment by cjsfj** [comment]
I see what you're saying.. It's weird because they actually set it up to point to your GitHub repo.

I wonder if adding the release on your repo would update the version downstream?

**Comment by luisiam** [comment]
I know it's linked. However, I need to run `npm publish` to update the repo in npm whenever I release an update. NPM won't pull updated automatically from GitHub. Since I don't own that under npm, I can never run `npm publish` on the plugin.

**Comment by cjsfj** [comment]
Well for what it's worth I still think it's a good idea to tag releases each time to you bump the version.

Thank you again for this plugin. Makes life easier for a lot of folks ;)

CJ

**Comment by luisiam** [comment]
I am very new to GitHub and I was not aware of tagging. Did a bit research and added a 0.3.0 tag on GitHub now. Will tag releases every time afterwards.
