### ISSUE TITLE
Closing when closed

### ISSUE THREAD

**Issue by jcleek** [luisiam/homebridge-liftmaster2#12]
Using the MyQ Internet Gateway (http://www.chamberlain.com/smartphone-control-products/smartphone-connectivity/myq-internet-gateway). 

The plugin works to open and close, but when I ask the status with "is the garage door opener closed" Siri responds with "Your Garage Door Opener is closing". The Pi clearly shows ""Garage Door Opener is closed".

I just upgraded my setup and installed version 2. The previous version did not do this. Any idea on resolving?

**Comment by luisiam** [comment]
If the log shows the correct state, the correct state is sent to HomeKit. Not sure why Siri is not reporting the correct state.

Does that only happen on Closed/Closing combo? How about the Opened/Opening combo? What if you ask Siri differently?
`Is the garage door opener opened`
`What is the status of the garage door opener`

**Comment by jcleek** [comment]
Is the garage door opener closed
Is the garage door opener opened
What is the status of the garage door opener

All three yield "Your Garage Door Opener is closing"

**Comment by luisiam** [comment]
I will take a look into this when I have time.

**Comment by jcleek** [comment]
Standing by to test...

**Comment by luisiam** [comment]
I actually don't have that problem. 

![img_0084](https://cloud.githubusercontent.com/assets/16310467/20954216/26848664-bbee-11e6-8a94-898345148005.PNG)

**Comment by jcleek** [comment]
I will test with my wife's phone tonight as it may be a phone issue. As I mentioned, the console tells me the door is closed. Siri is the one that says "closing". I will report back what I find.

**Comment by jcleek** [comment]
Wifes phone gives the same response, so I burned my Pi back down to nothing and reinstalled everything. I still get the same response from both phones.
![2016-12-07 20 19 35](https://cloud.githubusercontent.com/assets/16121417/20993785/8b043040-bcba-11e6-8d9c-f0a259cfa1d6.png)

**Comment by jcleek** [comment]
This is what I see in the console.
![pi](https://cloud.githubusercontent.com/assets/16121417/20994049/0b124ed8-bcbc-11e6-9e05-96acb12d6ef8.png)

**Comment by jcleek** [comment]
I I get the same response on the open side. When it is open, Siri says it is opening. Console says "Garage Door is open".

**Comment by luisiam** [comment]
Just want to make sure. Are you on the latest version 0.3.0?

**Comment by jcleek** [comment]
Not sure how to get the version of the plugin, but I installed it with:

npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git

**Comment by jcleek** [comment]
Ok, got it: homebridge-liftmaster2@0.3.0 (git+https://github.com/luisiam/homebridge-liftmaster2.git#fb95fb616868f284d27dbf7f976e8f80e4382a88)

**Comment by jcleek** [comment]
I rebuilt everything and used the Liftmaster original plugin and have no issues.

**Comment by luisiam** [comment]
That's weird because the plugin never reports an `opening` or `closing` state after 0.3.0. It will only report `open` or `closed`.

Try to double check all the state of your garage door opener using the unofficial api document and report back here.
http://docs.unofficialliftmastermyq.apiary.io/

Since I am using a different model, I cannot really check on that.

**Comment by jcleek** [comment]
Took me a few minutes to figure out the API but I have 4 distinct responses from the gateway:

Closed:  {"AttributeValue":"2","UpdatedTime":"1481480440618","ReturnCode":"0","ErrorMessage":"","CorrelationId":"407736cc-4294-4a98-852e-e1a7b92e2c50"}
Opening: {"AttributeValue":"4","UpdatedTime":"1481490811911","ReturnCode":"0","ErrorMessage":"","CorrelationId":"f5f8abd4-dad4-423d-b5b4-f02c15b92050"}
Open:    {"AttributeValue":"1","UpdatedTime":"1481490823247","ReturnCode":"0","ErrorMessage":"","CorrelationId":"825d03ec-9761-483d-8dd2-9742e9b06982"}
Closing: {"AttributeValue":"5","UpdatedTime":"1481490852935","ReturnCode":"0","ErrorMessage":"","CorrelationId":"93281f68-851d-47a4-9f1b-d9f244be8609"}

**Comment by luisiam** [comment]
The plugin will always return `open` unless the `AttributeValue` is `2`. I am not sure why your Siri is not reporting the correct state. As I mentioned earlier, the state you can see from the log is already the state reported to HomeKit.

How about the state in the Apple Home app or other HomeKit app? Is the state reported correctly?

**Comment by jcleek** [comment]
With the old liftmaster plugin it works correctly for all 4 states in the home app: open, closed, opening and closing. I do not have liftmaster2 installed anymore because it wasn't giving accurate status.

**Comment by tmur11** [comment]
@luisiam how come you closed this? This to me seems like an open issue, no?

**Comment by jcleek** [comment]
In fairness I no longer have the plugin installed so I cannot test. The original plugin continues to work as expected so I have no need to change.
