### ISSUE TITLE
garage doesn't always close on first request

### ISSUE THREAD

**Issue by votran** [luisiam/homebridge-liftmaster2#14]
I am currently having an issue with the garage not closing on the first attempt. Siri would indicate that the action was completed but nothing happens. A second request to have Siri close the garage door seems to always solve the issue. Further, if I'm executing the command manually through the homekit app, the button just hangs on closing status with the door never actually closing. A quick tap to override with the open command followed by another tap to close the garage also solves the issue.  I am currently using the default advanced configuration, with polling, listed on the readme. Thanks.

**Comment by luisiam** [comment]
Which MyQ device are you using?

**Comment by votran** [comment]
I am currently using the Chamberlain MyQ Internet Gateway CIGBU/C. I'd also like to note that I typically send the request to open the garage door via Siri when I am approaching my house while on my cellular network and out of my home wifi range so there is a moment between sending requests, to open and close the garage door, that I switch from cellular to my home wifi. This seems to consistently cause the aforementioned issue vs testing it on my home wifi, without breaking the connection, only causing the issue to happen sporadically.

**Comment by luisiam** [comment]
Do you see the corresponding log in homebridge when you try on the first attempt?

**Comment by votran** [comment]
This is the log of the most recent occurrence which was just now as I came home for lunch:

Jan 18 12:14:50 raspberrypi homebridge[2478]: [1/18/2017, 12:14:50 PM] [Front Gate] Setting state to 0
Jan 18 12:14:50 raspberrypi homebridge[2478]: [1/18/2017, 12:14:50 PM] [Front Gate] Triggering GarageDoor Relay
Jan 18 12:14:54 raspberrypi homebridge[2478]: [1/18/2017, 12:14:54 PM] [Front Gate] Setting state to 1
Jan 18 12:14:54 raspberrypi homebridge[2478]: [1/18/2017, 12:14:54 PM] [Front Gate] Turning off GarageDoor Relay
Jan 18 12:15:51 raspberrypi homebridge[2478]: [1/18/2017, 12:15:51 PM] [MyQ] Logged in with MyQ user ID 0
Jan 18 12:15:51 raspberrypi homebridge[2478]: [1/18/2017, 12:15:51 PM] [MyQ] Garage Door Opener is set to open.
Jan 18 12:16:58 raspberrypi homebridge[2478]: [1/18/2017, 12:16:58 PM] [MyQ] Logged in with MyQ user ID 0
Jan 18 12:16:58 raspberrypi homebridge[2478]: [1/18/2017, 12:16:58 PM] [MyQ] Garage Door Opener is set to closed.
Jan 18 12:17:09 raspberrypi homebridge[2478]: [1/18/2017, 12:17:09 PM] [MyQ] Logged in with MyQ user ID 0
Jan 18 12:17:09 raspberrypi homebridge[2478]: [1/18/2017, 12:17:09 PM] [MyQ] Garage Door Opener is set to closed.
lines 1030-1055/1055 (END)

------------------------------------------------------

It appears to successfully send the command but the garage door doesn't actually close until I send a second command to close which is always successful. Requests to open the garage door doesn't seem to be affected.

**Comment by luisiam** [comment]
Will there be chances that you are switch from WiFi to cellular or vice versa when you are issuing the command?

**Comment by votran** [comment]
I had initially thought that may have been the cause but I recently tested the plugin, while standing right outside of my garage, making sure I was connected to my home wifi the whole time and the issue is still present.

**Comment by votran** [comment]
Upon further testing today, I think I may have discovered what causes the issue of the garage door not closing on first request. It seems while testing the plugin today, the garage not closing on the first request only happens if I trigger the safety sensor at any point after the garage door has been opened (i.e. driving the car into the garage after it has opened). So for instance, while testing, I can successfully open and close the garage door repeatedly on the first request if I never at any point enter the garage, tripping the safety sensor. But after opening the garage door, entering and exiting the garage will cause the garage to not close on the first request (making sure I am clear from the safety sensor before sending the request to close the garage door). What could be the reason for this behavior?

**Comment by luisiam** [comment]
I believe it has to do with the behavior of your garage opener. I am using MyQ Garage which doesn't has connection to the safety sensor and I have no problem with it.

In the plugin point of view, as long as the log exists, the request is sent to the MyQ server.

How about using the MyQ app? Do you always need to issue the closing command twice?

**Comment by votran** [comment]
I didn't even think to retest my findings with the MyQ app after discovering how to reliably replicate the issue. I had previously tried a few times with the MyQ app without knowing to trip the safety sensors and it obviously worked without any problems so I dismissed it. But after testing it again with the MyQ app and deliberately tripping the safety sensors, it does indeed display the same issue of not closing. So it seems this is a MyQ/hardware issue. Thanks for all your help and I apologize for the oversight.
