### ISSUE TITLE
LiftMaster2 Crashing Homebridge Server

### ISSUE THREAD

**Issue by mmaxwell5** [luisiam/homebridge-liftmaster2#15]
About once a day my homebridge server is crashing with the following in the error log:

> undefined:1
> undefined
> ^
> 
> SyntaxError: Unexpected token u
>     at Object.parse (native)
>     at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster2/index.js:237:21)
>     at self.callback (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:186:22)
>     at emitOne (events.js:82:20)
>     at Request.emit (events.js:169:7)
>     at Request.onRequestError (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:845:8)
>     at emitOne (events.js:77:13)
>     at ClientRequest.emit (events.js:169:7)
>     at TLSSocket.socketErrorListener (_http_client.js:259:9)
>     at emitOne (events.js:77:13)
>     at TLSSocket.emit (events.js:169:7)
>     at emitErrorNT (net.js:1250:8)
>     at doNTCallback2 (node.js:429:9)
>     at process._tickCallback (node.js:343:17)

Below is the configuration I have for homebridge-liftmaster2:

> 		"platform": "LiftMaster2",
> 	  	"name": "Garage Door",
> 		"username": "*********",
> 		"password": "*******",
> 		"openDuration": 13,
> 		"closeDuration": 13,
> 		"polling": true,
> 		"longPoll": 30,
> 		"shortPoll": 5,
> 		"shortPollDuration": 120

Any help would be much appreciated.  Thank you in advance.  I am happy to try anything that would help resolve this.

**Comment by jmesterh** [comment]
I am having the same exact error also.

**Comment by luisiam** [comment]
I think I know the issue. I will need to think of a way to improve that.

**Comment by mmaxwell5** [comment]
I am having an issue where my home bridge server is crashing multiple times a day due to this error. 

Any progress on a fix? Is there anything I can do to help? 

Thank you in advance.

**Comment by luisiam** [comment]
Install the new patch with `npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git#d89e3091023b75643b431356b19400426c161f37` and report back.

**Comment by mmaxwell5** [comment]
Thank you,

I have applied the update. I should know within a week or so if it is better.  I will keep you posted.


Michael Maxwell

**Comment by cakefornoreason** [comment]
I hadn't been having problems, but just today started getting an odd error that persists even after installing the patch. It's similar to the ones people have mentioned, but not exactly the same. I've pasted the Homebridge error log below, but to me the interesting part is the fact that it seems the MyQ web service is denying the request. I've checked my password and it's correct, and the exact same credentials work fine in the MyQ app or on the website.

Any idea what's up?

```
SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster2/index.js:186:21)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595389183509673]</body></html>
```

**Comment by twentworth12** [comment]
I'm getting the same error as @cakefornoreason.

**Comment by rd9082** [comment]
Same here. started getting the error today. tried installing and reinstalling as well as installing the new patched version you posted a few weeks ago. here is an image of the full error I'm getting:

![image](https://cloud.githubusercontent.com/assets/25757195/22909576/c98d1f6e-f222-11e6-996c-b6aa1b7e324c.png)

**Comment by luisiam** [comment]
Looks like Chamberlain is blocking this unofficial API request.

**Comment by reallybman** [comment]
Just started getting this today

**Comment by pponce** [comment]
me too!

**Comment by luisiam** [comment]
This is a separate issue. Discuss on #18
