### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by leblanc007** [luisiam/homebridge-liftmaster2#16]
I'm new to homebridge, but discovered this when I wanted to control my MyQ Garage Door with Siri and HomeKit.  I have a Mac Mini at home that is always on.  I installed homebridge and the "homebridge-liftmaster2" plugin on that computer without any issues.  I then set up my "config.json" per the following:

{
	"bridge": {
		"name": "leblanc-homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"

	},

	"platforms": [{
		"platform": "LiftMaster2",
		"username": "XXXXX",
		"password": "XXXXX"
	}]

}

After setting everything up, I went to Terminal and typed in "homebridge".  Everything appeared to work without issue.  If I then quit Terminal (and therefore homebridge) and start homebridge again, I get the following error:

Homebridge is running on port 51826.
[1/5/2017, 4:05:12 PM] Logged in with MyQ user ID 0
[1/5/2017, 4:05:13 PM] Error 'Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b965638d-72fb-4744-b92d-80ce22e732dc'
[1/5/2017, 4:05:13 PM] undefined is removed from HomeBridge.

If I then go into my "~/.homebridge" folder and delete the "persist" folder and files in the "accessories" folder, and run homebridge again, it works without the above error.  However, every time after the initial first start it gives me that error.  Any ideas on why I am getting this error?

As a second issue, I have 2 garage doors hooked up through MyQ account.  When homebridge logs into my account via Terminal, it never warns me that I have two garage doors and gives me each garage doors name and ID.  I see with the "Liftmaster" plugin version 1, that it is supposed to do that.  Any ideas on how to set up each garage door?

Also, I tried to view a homebridge log file to see if that tells me anything, but I couldn't find one that is supposedly located in my "/var/log/" folder.  How do I see the log file for the errors?

Thanks in advance.

**Comment by leblanc007** [comment]
Nevermind... When I added the homebridge to homekit on my phone, it added both of my garage doors.  I still do the get the error every time I stop and restart homebridge saying that it cannot add a bridged accessory with the same UUID.  However, everything appears to still work.

**Comment by russmo** [comment]
I also get the exact same error as @leblanc007  "cannot add a bridged accessory with the same UUID" whenever I restart Homebridge. I only have one garage door.  It works perfectly when launched on a clean install.

Unlike @leblanc007, homebridge is not connecting to homekit when this happens.  Everything just says "updating" and remains unresponsive.  This means that homebridge/homekit will die anytime my server has to reboot.  I have had to revert to using homebridge-chamberlain or homebridge-liftmaster, which works without issue.

Any thoughts on how I can get homebridge-liftmaster2 working properly?
