### ISSUE TITLE
Assurelink

### ISSUE THREAD

**Issue by shadjhansen** [luisiam/homebridge-liftmaster2#19]
luisiam,

Thank you so much for creating the LiftMaster2 plugin for the garage door opener integration with Homebridge. With my liftmaster (Assurelink) implementation at home, I also utilize the 823LM lights managed by the liftmaster gateway. Do you know if there is a way to manage those as well from the plugin? I did find an index.js file that was built for the MyQ plugin under API 1.0 of Homebridge that includes Light control but it does not work with the LiftMaster2 plugin.

Let me know if this could be possible?
Thanks,
shadjhansen

**Comment by luisiam** [comment]
I don't own any of those therefore I cannot implement that.
