### ISSUE TITLE
Two devices are showing up instead of one

### ISSUE THREAD

**Issue by mmaxwell5** [luisiam/homebridge-liftmaster2#21]
Thank you @luisiam for getting the plugin working with your latest update.  Much appreciated.  

I am having one problem with the new update.  I am having two accessories show up ("Garage Door" and "Garage Door Opener") in homekit when I only have one Garage Door MYQ device. 

The "Garage Door Opener" appears to work just fine.  The "Garage Door" does not work and just gives me the error below:

Error setting Garage Door state: {"ReturnCode":"312","ErrorMessage":"This garage door is only set up to have its status monitored. (312)","CorrelationId":"425f3d39-1791-47f0-ba2b-34a9c24a3869"}

I have tried clearing my cachedaccessories and completely removing homebridge-liftmaster2 and installing again.  I am using the MYQ with the garage door sensor. 

Any help would be great!  Thank you in advance.  

![photo-2017-02-17-22-01-45_157f9bb0-9383-4189-9000-0c1a3d768649](https://cloud.githubusercontent.com/assets/16730904/23090174/e68d090c-f55c-11e6-9220-f26fe37e433d.PNG)

**Comment by jcarr2000** [comment]
I'm seeing this issue as well.  Running homebridge 0.4.16 on macOS.

Let me know if I can post any logs to help debug this issue.

**Comment by luisiam** [comment]
Please try latest version 0.4.2

**Comment by mmaxwell5** [comment]
That seemed to have fixed it for me.  Thank you very much!  
I really appreciate all your work on this plugin.

**Comment by iRayanKhan** [comment]
Getting this issue aswell
