### ISSUE TITLE
Flip the Open/Close state?

### ISSUE THREAD

**Issue by depaulsunny** [luisiam/homebridge-liftmaster2#27]
Hello,

I have a very odd situation and I'm hoping you can help. My garage door is a swing-open, carriage-style garage door. It uses an extender arm connected to a lift master garage door opener.

The garage door opener itself works great and has been working well for a long time now. However, because of how the garage door opener is configured, when my garage door says its open, its actually closed and vice versa. 

When I login into myQ to check whether the garage door is open or not, I have to mentally flip the status.

I think you may know where I'm going with this...

Could you provide me a modified code so that in the home app, the state and commands would go as reversed?

E.g: When myQ states garage is open, Home app shows the garage as closed. When I ask home app or Siri to open the garage, it sends the command to myQ to close the garage.

I tried to modify index.js file and make it so and was partially successful. I got the state to show as reversed by modifying section starting at line 311. But, I had issues giving commands.

I'm not good with js and I figured its easier to ask if you could modify other sections as necessary.

Thanks in advance!

**Comment by luisiam** [comment]
You will need to flip the state here as well:
https://github.com/luisiam/homebridge-liftmaster2/blob/master/index.js#L355

**Comment by depaulsunny** [comment]
I did that section as well but Home app still had issues giving commands. Is there another section I need to modify?

**Comment by luisiam** [comment]
Those 2 places should be the only place to modify. One for get state and one for set state.

**Comment by depaulsunny** [comment]
Ok thanks. Can you please take a look at my code and make sure I didn't do this wrong?

On line 311, I changed the code to this:

`
// Determine the current door state
--
  | var newState;
  | if (thisDoorState === "1") {
  | newState = Characteristic.CurrentDoorState.CLOSED;
  | } else if (thisDoorState === "3") {
  | newState = Characteristic.CurrentDoorState.STOPPED;
  | } else {
  | newState = Characteristic.CurrentDoorState.OPEN;
  | }
`

and on line 355 I changed the code to this:
`
var liftmasterState = state === 1 ? "1" : "0";
`

Does that look right?
Thanks in advance for your help!

**Comment by luisiam** [comment]
Looks correct

**Comment by depaulsunny** [comment]
Thanks! I'll try it out tonight and let you know if it works.

**Comment by depaulsunny** [comment]
It looks like it worked! Thank you so much!
