### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by kadecole** [luisiam/homebridge-liftmaster2#29]
I keep getting an error when using this plugin:

> undefined:1
> <html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[4251746500036932579]</body></html>

>SyntaxError: Unexpected token <
>   at Object.parse (native)
>   at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
>   at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:188:22)
>    at emitTwo (events.js:87:13)
>    at Request.emit (events.js:172:7)
>    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1171:10)
>    at emitOne (events.js:77:13)
>    at Request.emit (events.js:169:7)
>    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1091:12)
>    at IncomingMessage.g (events.js:260:16)

**Comment by kadecole** [comment]
The problem was Issue #11 . I needed to run the following and not install from npm directly. 

`npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git`

**Comment by svicino** [comment]
This just helped me with the same issue. Maybe should be in a FAQ?
