### ISSUE TITLE
Error on startup - not finding credentials?

### ISSUE THREAD

**Issue by wparsons-360insights** [luisiam/homebridge-liftmaster2#43]
I'm getting this error when homebridge starts up:

`[homebridge-liftmaster2.LiftMaster2] Please setup MyQ login information!`

The credentials are in the config.json file, and are definitely correct (copied/pasted and was able to log into the site directly).  I'm not able to find anything for it in the MyQ app, so I think the error isn't a false warning.  The WeMo stuff still works just fine as well.

Here's my config:

`{
        "bridge": {
                "name": "Homebridge",
                "username": "XX:XX:XX:XX:XX:XX",
                "port": XXXXX,
                "pin": "XXX-XX-XXX"
        },
        "platforms": [{
                "platform": "BelkinWeMo",
                "name": "WeMo Platform"
        }, {
                "platform": "LiftMaster2",
                "name": "Liftmaster",
                "username": "xxxxxxxx@xxxx.xxx",
                "password": "xxxxxxxx"
        }]
}`

Any suggestions?

**Comment by wparsons-360insights** [comment]
Update - I've been starting homebridge with `sudo systemctl start homebridge`  if I just navigate to the folder and run homebridge directly it works, and finds the devices (two openers) from my account.  Seems strange that it behaves differently like this, if anything I would expect it to fail when being run by my local account vs sudo.

**Comment by wparsons-360insights** [comment]
Dug in a bit more and added some logging to see what was happening, when running by systemctl it's not getting the config object passed.  Temporarily fixed it by adding my username and password to the default object used for config until I can figure out why it's not being passed in on startup.

**Comment by iRayanKhan** [comment]
Please close this issue if it's fixed

**Comment by wparsons-360insights** [comment]
D'Oh, thought I already had closed it.
