### ISSUE TITLE
Simply Can't Install This Plugin Successfully

### ISSUE THREAD

**Issue by chicobug** [luisiam/homebridge-liftmaster2#47]
Man, I'm pulling my hair out. Trying to install the Liftmaster2 plugin on my Pi. Ive got the Pi running Docker with no other plugins installed. I've tried installing the plugin using this command:

npm install -save git+https://github.com/luisiam/homebridge-liftmaster2.git

And while installing it gives me this message, which isn't clear to me that it's even installed:

(node:16879) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
homebridge-liftmaster2@0.4.3 node_modules/homebridge-liftmaster2
└── node-fetch@1.7.3 (is-stream@1.1.0, encoding@0.1.12)

I've also used the  homebridge-config-ui-x plugin to access Homekit with the browser GUI. When I install the Liftmaster2 plugin there, I get this looping startup error:

Error: The requested platform 'LiftMaster2' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

I have modified my JSON Config file to accommodate the plugin and it looks like this:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": [
        {
            "platform": "LiftMaster2",
            "username": "_redacted_",
            "password": "_redacted_"
        }
    ]
}

As soon as I edit my JSON file to the above, the Homebridge Service ceases to run. But if I don't edit the JSON file then the service does run (albeit with no active plugin, so it does nothing). 

I should also add, if it's not already completely apparent, that I'm a noob and am trying to troubleshoot this with limited knowledge.

Anyone see anything that I should be doing differently?

**Comment by chicobug** [comment]
Also, when I install the Liftmaster2 plugin via the web browser interface, I then get this error:

SyntaxError: Unexpected token < in JSON at position 0

at JSON.parse (<anonymous>)

at Request.\_callback (/homebridge/node\_modules/homebridge-liftmaster2/index.js:249:23)

at Request.self.callback (/homebridge/node\_modules/request/request.js:185:22)

at emitTwo (events.js:126:13)

at Request.emit (events.js:214:7)

at Request.<anonymous> (/homebridge/node\_modules/request/request.js:1161:10)

at emitOne (events.js:116:13)

at Request.emit (events.js:211:7)

at IncomingMessage.<anonymous> (/homebridge/node\_modules/request/request.js:1083:12)

at Object.onceWrapper (events.js:313:30)

&#x200B;

&#x200B;

Argh!

**Comment by iRayanKhan** [comment]
Use LiftMaster (1) aka the original liftmaster plugin it works great for me.

**Comment by iRayanKhan** [comment]
Try this config for LiftMaster 2
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Homebridge",
    "accessories": [],
    "platforms": [
        {
            "platform": "LiftMaster2",
            "username": "redacted",
            "password": "redacted"
        }
    ]
}

**Comment by chicobug** [comment]
So last weekend my Home Hub just stopped working. I worked on resetting it today and just couldn't get the install to work. I pressed some random buttons on the hub and somehow it then allowed me to pair everything and get it going. When I rebooted the Pi, lo and behold, Homebridge was up and running. I have no idea what happened. I never touched the JSON file and somehow it all started working. We'll see how long it lasts, as I'm not convinced that this MYQ device is very robust.

But thanks to all for the help and input.

**Comment by iRayanKhan** [comment]
@chicobug is it still working for you?

**Comment by chicobug** [comment]
@irayankhan Yes, it actually is! And I have no idea why. I suspect the issue was with Loftmaster more than anything. They updated their app and it started working. Correlation? Causation. Dunno, but it’s working beautifully now. 

Also if interest to someone, maybe - I was messing with my router and turned on WPS. It caused HomeKit to not be available outside the home network. Turned off WPS and it started working again.

**Comment by iRayanKhan** [comment]
@chicobug Mine was working and now it stopped. Imma try it out thanks for the reply!

**Comment by chicobug** [comment]
FYI, I stuck with Liftmaster2. Maybe try it if you haven’t already?

**Comment by iRayanKhan** [comment]
@chicobug I get an error that is listed as the latest issue posted rn. No idea why it's suddenly happened.

**Comment by chicobug** [comment]
I wish I was smart enough to help out. I’m pretty boggled by the whole thing. I know just enough to get myself into trouble.

**Comment by iRayanKhan** [comment]
Are you using a raspberry pi?

**Comment by chicobug** [comment]
Yup

**Comment by iRayanKhan** [comment]
Fixed this with Chamberlain plugin. Thanks for the help!
Also you should probs close this issue.

**Comment by chicobug** [comment]
Glad to hear it. And yeah, I’ll close.
