### ISSUE TITLE
multiple devices

### ISSUE THREAD

**Issue by iflore** [luisiam/homebridge-liftmaster2#5]
Grateful for any directions / instructions on how to use liftmaster2 platform to control more than one device.  I installed one device, which works fine via homebridge and continues to do so after I added a second device (first was a garage door; second is a driveway gate).  both garage door and driveway gate work reliably through myq liftmaster app.  but homebridge does not recognize the second device - the gate.  do i need to use deviceIDs in the config.json file or something?  how would i find my deviceIDs? 

Here's the pertinent part of my config file.  Thanks in advance. 

	{	"platform": "LiftMaster2",
	   	"username": "xxxxxxxx@gmail.com",
   		"password": "xxxxxxxx"
	}

Terminal states:  "... [MyQ] Logged in with MyQ user ID 0"

**Comment by luisiam** [comment]
What's the model of that?

**Comment by iflore** [comment]
The model of the liftmaster devices?   The first is an older garage opener that is now controlled through the MYQ wall panel 888LM; the second is LA500PKGU gate operator which has myq built in.  Both connect to the net through the internet gateway 828LM MyQ.  Both work fine with the MyQ app...  Thank you!

**Comment by luisiam** [comment]
Since I don't have that type of device. I cannot do any testing on my side. If you really want to have it implemented, you can provide me so info and I can try to implement it.

Add `self.platformLog(json);` to line 305
https://github.com/luisiam/homebridge-liftmaster2/blob/master/index.js#L305

Give me that portion of the log.

**Comment by iflore** [comment]
Thanks very much.  I’m a complete novice though.  If you can walk me through what I need to do, I’ll do my best.  Thanks again.

**Comment by luisiam** [comment]
Run `npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944`

Get me the complete log

**Comment by luisiam** [comment]
Run `npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git#9a5695a362897de84dae241226817c3cf657ea57`

Restart homebridge and give me the full log

**Comment by iflore** [comment]
indyflore$ SUDO npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
homebridge-liftmaster2@0.1.2 /usr/local/lib/node_modules/homebridge-liftmaster2
├── chalk@1.1.3 (supports-color@2.0.0, escape-string-regexp@1.0.5, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
└── request@2.75.0 (tunnel-agent@0.4.3, aws-sign2@0.6.0, forever-agent@0.6.1, oauth-sign@0.8.2, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.12, form-data@2.0.0, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)

*********

Indys-Mini-2:~ indyflore$ npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! path /usr/local/lib/node_modules/homebridge-liftmaster2
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rmdir

npm ERR! Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/homebridge-liftmaster2'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/homebridge-liftmaster2']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: '/usr/local/lib/node_modules/homebridge-liftmaster2' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/homebridge-liftmaster2'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/homebridge-liftmaster2']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/homebridge-liftmaster2' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Macintosh HD/Users/indyflore/npm-debug.log


******

COMPLETE LOG:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
6 silly cache add   null ]
7 verbose cache add spec git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: 'git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
8 silly cache add   spec: 'git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
8 silly cache add   type: 'hosted',
8 silly cache add   hosted:
8 silly cache add    { type: 'github',
8 silly cache add      ssh: 'git@github.com:luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
8 silly cache add      sshUrl: 'git+ssh://git@github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
8 silly cache add      httpsUrl: 'git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
8 silly cache add      gitUrl: 'git://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
8 silly cache add      shortcut: 'github:luisiam/homebridge-liftmaster2#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
8 silly cache add      directUrl: 'https://raw.githubusercontent.com/luisiam/homebridge-liftmaster2/6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944/package.json' } }
9 verbose addRemoteGit caching git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
10 verbose addRemoteGit git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 is a repository hosted by github
11 silly tryClone cloning git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 via git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
12 verbose tryClone https-github-com-luisiam-homebridge-liftmaster2-git-b534d6cf not in flight; caching
13 verbose correctMkdir /Volumes/Macintosh HD/Users/indyflore/.npm/_git-remotes correctMkdir not in flight; initializing
14 info git [ 'config', '--get', 'remote.origin.url' ]
15 silly validateExistingRemote git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 remote.origin.url: https://github.com/luisiam/homebridge-liftmaster2.git
16 verbose validateExistingRemote git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 is updating existing cached remote /Volumes/Macintosh HD/Users/indyflore/.npm/_git-remotes/https-github-com-luisiam-homebridge-liftmaster2-git-b534d6cf
17 info git [ 'fetch', '-a', 'origin' ]
18 verbose updateRemote git fetch -a origin (https://github.com/luisiam/homebridge-liftmaster2.git)
19 verbose correctMkdir /Volumes/Macintosh HD/Users/indyflore/.npm/_git-remotes correctMkdir not in flight; initializing
20 verbose setPermissions git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 set permissions on /Volumes/Macintosh HD/Users/indyflore/.npm/_git-remotes/https-github-com-luisiam-homebridge-liftmaster2-git-b534d6cf
21 verbose resolveHead git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 original treeish: 6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
22 info git [ 'rev-list', '-n1', '6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944' ]
23 silly resolveHead git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 resolved treeish: 6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
24 verbose resolveHead git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 resolved Git URL: git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
25 silly resolveHead Git working directory: /var/folders/zr/9x27vlgx0yx5_77p6vsfrqp40000gn/T/npm-50359-50be9f65/git-cache-fa1efdec7eeb/6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
26 info git [ 'clone',
26 info git   '/Volumes/Macintosh HD/Users/indyflore/.npm/_git-remotes/https-github-com-luisiam-homebridge-liftmaster2-git-b534d6cf',
26 info git   '/var/folders/zr/9x27vlgx0yx5_77p6vsfrqp40000gn/T/npm-50359-50be9f65/git-cache-fa1efdec7eeb/6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944' ]
27 verbose cloneResolved git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 clone Cloning into '/var/folders/zr/9x27vlgx0yx5_77p6vsfrqp40000gn/T/npm-50359-50be9f65/git-cache-fa1efdec7eeb/6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944'...
27 verbose cloneResolved done.
28 info git [ 'checkout', '6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944' ]
29 verbose checkoutTreeish git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944 checkout Note: checking out '6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944'.
29 verbose checkoutTreeish
29 verbose checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
29 verbose checkoutTreeish changes and commit them, and you can discard any commits you make in this
29 verbose checkoutTreeish state without impacting any branches by performing another checkout.
29 verbose checkoutTreeish
29 verbose checkoutTreeish If you want to create a new branch to retain commits you create, you may
29 verbose checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
29 verbose checkoutTreeish
29 verbose checkoutTreeish   git checkout -b <new-branch-name>
29 verbose checkoutTreeish
29 verbose checkoutTreeish HEAD is now at 6e35d07... Update index.js
30 verbose addLocalDirectory /Volumes/Macintosh HD/Users/indyflore/.npm/homebridge-liftmaster2/0.1.2/package.tgz not in flight; packing
31 verbose correctMkdir /Volumes/Macintosh HD/Users/indyflore/.npm correctMkdir not in flight; initializing
32 verbose tar pack [ '/Volumes/Macintosh HD/Users/indyflore/.npm/homebridge-liftmaster2/0.1.2/package.tgz',
32 verbose tar pack   '/var/folders/zr/9x27vlgx0yx5_77p6vsfrqp40000gn/T/npm-50359-50be9f65/git-cache-fa1efdec7eeb/6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944' ]
33 verbose tarball /Volumes/Macintosh HD/Users/indyflore/.npm/homebridge-liftmaster2/0.1.2/package.tgz
34 verbose folder /var/folders/zr/9x27vlgx0yx5_77p6vsfrqp40000gn/T/npm-50359-50be9f65/git-cache-fa1efdec7eeb/6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
35 verbose addLocalTarball adding from inside cache /Volumes/Macintosh HD/Users/indyflore/.npm/homebridge-liftmaster2/0.1.2/package.tgz
36 verbose correctMkdir /Volumes/Macintosh HD/Users/indyflore/.npm correctMkdir not in flight; initializing
37 verbose addRemoteGit data._from: git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
38 verbose addRemoteGit data._resolved: git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944
39 silly cache afterAdd homebridge-liftmaster2@0.1.2
40 verbose afterAdd /Volumes/Macintosh HD/Users/indyflore/.npm/homebridge-liftmaster2/0.1.2/package/package.json not in flight; writing
41 verbose correctMkdir /Volumes/Macintosh HD/Users/indyflore/.npm correctMkdir not in flight; initializing
42 verbose afterAdd /Volumes/Macintosh HD/Users/indyflore/.npm/homebridge-liftmaster2/0.1.2/package/package.json written
43 silly install resolved [ { name: 'homebridge-liftmaster2',
43 silly install resolved     version: '0.1.2',
43 silly install resolved     description: 'LiftMaster plugin for HomeBridge (API 2.0): https://github.com/nfarina/homebridge',
43 silly install resolved     repository:
43 silly install resolved      { type: 'git',
43 silly install resolved        url: 'git://github.com/luisiam/homebridge-liftmaster2.git' },
43 silly install resolved     keywords: [ 'homebridge-plugin' ],
43 silly install resolved     author: { name: 'Luis Iam' },
43 silly install resolved     license: 'ISC',
43 silly install resolved     bugs: { url: 'https://github.com/luisiam/homebridge-liftmaster2/issues' },
43 silly install resolved     homepage: 'https://github.com/luisiam/homebridge-liftmaster2#readme',
43 silly install resolved     engines: { node: '>=0.12.0', homebridge: '>=0.3.0' },
43 silly install resolved     dependencies: { request: '^2.49.0', chalk: '^1.1.3' },
43 silly install resolved     gitHead: '6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
43 silly install resolved     readme: '# homebridge-liftmaster2\nLiftMaster Plugin for [HomeBridge](https://github.com/nfarina/homebridge) (API 2.0)\n\nOlder verion using API 1.0: [homebridge-liftmaster](https://github.com/nfarina/homebridge-liftmaster)\n\n# Installation\n1. Install homebridge using `npm install -g homebridge`.\n2. Install this plugin using `npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git`.\n3. Update your configuration file. See configuration sample below.\n\n# Configuration\nEdit your `config.json` accordingly. Configuration sample:\n ```\n"platforms": [{\n    "platform": "LiftMaster2",\n    "username": "email@email.com",\n    "password": "password"\n}]\n```\n\n### Advanced Configuration (Optional)\nThis step is not required. HomeBridge with API 2.0 can handle configurations in the HomeKit app.\n```\n"platforms": [{\n    "platform": "LiftMaster2",\n    "username": "email@email.com",\n    "password": "password",\n    "longPoll": 300,\n    "shortPoll": 5,\n    "shortPollDuration": 120\n}]\n\n```\n\n| Fields            | Description                                                   | Required |\n|-------------------|---------------------------------------------------------------|----------|\n| platform          | Must always be `LiftMaster2`.                                 | Yes      |\n| username          | Your MyQ account email.                                       | Yes      |\n| password          | Your MyQ account password.                                    | Yes      |\n| longPoll          | Normal polling interval in `s` (Default 300s).                | No       |\n| shortPoll         | Polling interval in `s` when door state changes (Default 5s). | No       |\n| shortPollDuration | Duration in `s` to use `shortPoll` (Default 120s).            | No       |\n',
43 silly install resolved     readmeFilename: 'README.md',
43 silly install resolved     _id: 'homebridge-liftmaster2@0.1.2',
43 silly install resolved     _shasum: '9b0d12a8f798c110d631456c3f42e991b5345e72',
43 silly install resolved     _from: 'git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944',
43 silly install resolved     _resolved: 'git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944' } ]
44 info install homebridge-liftmaster2@0.1.2 into /usr/local/lib
45 info installOne homebridge-liftmaster2@0.1.2
46 verbose installOne of homebridge-liftmaster2 to /usr/local/lib not in flight; installing
47 verbose correctMkdir /Volumes/Macintosh HD/Users/indyflore/.npm/_locks correctMkdir not in flight; initializing
48 verbose lock using /Volumes/Macintosh HD/Users/indyflore/.npm/_locks/homebridge-liftmaster2-46356f9d4ffa93af.lock for /usr/local/lib/node_modules/homebridge-liftmaster2
49 silly install write writing homebridge-liftmaster2 0.1.2 to /usr/local/lib/node_modules/homebridge-liftmaster2
50 verbose unbuild lib/node_modules/homebridge-liftmaster2
51 info preuninstall homebridge-liftmaster2@0.1.2
52 info uninstall homebridge-liftmaster2@0.1.2
53 verbose unbuild rmStuff homebridge-liftmaster2@0.1.2 from /usr/local/lib/node_modules
54 info postuninstall homebridge-liftmaster2@0.1.2
55 silly gentlyRm /usr/local/lib/node_modules/homebridge-liftmaster2 is being purged from base /usr/local
56 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/homebridge-liftmaster2
57 silly vacuum-fs purging /usr/local/lib/node_modules/homebridge-liftmaster2
58 verbose unlock done using /Volumes/Macintosh HD/Users/indyflore/.npm/_locks/homebridge-liftmaster2-46356f9d4ffa93af.lock for /usr/local/lib/node_modules/homebridge-liftmaster2
59 verbose stack Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/homebridge-liftmaster2'
59 verbose stack     at Error (native)
60 verbose cwd /Volumes/Macintosh HD/Users/indyflore
61 error Darwin 16.0.0
62 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "git+https://github.com/luisiam/homebridge-liftmaster2.git#6e35d07ae9cd0f18ed4b08d39e2dae3a6d016944"
63 error node v4.6.0
64 error npm  v2.15.9
65 error path /usr/local/lib/node_modules/homebridge-liftmaster2
66 error code EACCES
67 error errno -13
68 error syscall rmdir
69 error Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/homebridge-liftmaster2'
69 error     at Error (native)
69 error  { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/homebridge-liftmaster2']
69 error   errno: -13,
69 error   code: 'EACCES',
69 error   syscall: 'rmdir',
69 error   path: '/usr/local/lib/node_modules/homebridge-liftmaster2' }
70 error Please try running this command again as root/Administrator.
71 verbose exit [ -13, true ]
72 verbose unbuild lib/node_modules/homebridge-liftmaster2
73 info preuninstall homebridge-liftmaster2@0.1.2
74 info uninstall homebridge-liftmaster2@0.1.2
75 verbose unbuild rmStuff homebridge-liftmaster2@0.1.2 from /usr/local/lib/node_modules
76 info postuninstall homebridge-liftmaster2@0.1.2
77 silly gentlyRm /usr/local/lib/node_modules/homebridge-liftmaster2 is being purged from base /usr/local
78 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/homebridge-liftmaster2
79 silly vacuum-fs purging /usr/local/lib/node_modules/homebridge-liftmaster2
80 error error rolling back Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/homebridge-liftmaster2'
80 error error rolling back     at Error (native)
80 error error rolling back  { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/homebridge-liftmaster2']
80 error error rolling back   errno: -13,
80 error error rolling back   code: 'EACCES',
80 error error rolling back   syscall: 'rmdir',
80 error error rolling back   path: '/usr/local/lib/node_modules/homebridge-liftmaster2' }

**Comment by luisiam** [comment]
I think you need `sudo npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git#9a5695a362897de84dae241226817c3cf657ea57`

**Comment by iflore** [comment]
homebridge-liftmaster2@0.1.2 /usr/local/lib/node_modules/homebridge-liftmaster2
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
└── request@2.75.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.12, form-data@2.0.0, bl@1.1.2, hawk@3.1.3, har-validator@2.0.6, http-signature@1.1.1)

**Comment by iflore** [comment]
Indys-Mini-2:~ indyflore$ sudo npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git#9a5695a362897de84dae241226817c3cf657ea57
Password:
homebridge-liftmaster2@0.1.2 /usr/local/lib/node_modules/homebridge-liftmaster2
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
└── request@2.75.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.3.1, qs@6.2.1, node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.12, form-data@2.0.0, bl@1.1.2, hawk@3.1.3, har-validator@2.0.6, http-signature@1.1.1)
Indys-Mini-2:~ indyflore$ homebridge
[10/4/2016, 12:16:04 AM] Loaded plugin: homebridge-alarmdotcom
[10/4/2016, 12:16:04 AM] Registering platform 'homebridge-alarmdotcom.Alarmdotcom'
[10/4/2016, 12:16:04 AM] ---
[10/4/2016, 12:16:04 AM] ====================
[10/4/2016, 12:16:04 AM] ERROR LOADING PLUGIN homebridge-chamberlain:
[10/4/2016, 12:16:04 AM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/src/index.js:1:92)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:129:14)
[10/4/2016, 12:16:04 AM] ====================
[10/4/2016, 12:16:04 AM] Loaded plugin: homebridge-liftmaster
[10/4/2016, 12:16:04 AM] Registering accessory 'homebridge-liftmaster.LiftMaster'
[10/4/2016, 12:16:04 AM] ---
[10/4/2016, 12:16:04 AM] Loaded plugin: homebridge-liftmaster2
[10/4/2016, 12:16:04 AM] Registering platform 'homebridge-liftmaster2.LiftMaster2'
[10/4/2016, 12:16:04 AM] ---
[10/4/2016, 12:16:04 AM] Loaded plugin: homebridge-myq
[10/4/2016, 12:16:04 AM] Registering platform 'homebridge-myq.MyQ'
[10/4/2016, 12:16:04 AM] ---
[10/4/2016, 12:16:04 AM] Loaded plugin: homebridge-nest
[10/4/2016, 12:16:04 AM] Registering platform 'homebridge-nest.Nest'
[10/4/2016, 12:16:04 AM] ---
[10/4/2016, 12:16:04 AM] Loaded config.json with 0 accessories and 3 platforms.
[10/4/2016, 12:16:04 AM] ---
[10/4/2016, 12:16:04 AM] Loading 3 platforms...
[10/4/2016, 12:16:04 AM] Initializing Nest platform...
[10/4/2016, 12:16:04 AM] Fetching Nest devices.
[10/4/2016, 12:16:04 AM] Initializing LiftMaster2 platform...
[10/4/2016, 12:16:04 AM] [Security Panel] Initializing Alarmdotcom platform...
[10/4/2016, 12:16:04 AM] [Error: You did not specify {'token'} or {'clientId','clientSecret','code'}, one set of which is required for the new API]
[10/4/2016, 12:16:04 AM] Falling back to legacy API.
[10/4/2016, 12:16:05 AM] [MyQ] Logged in with MyQ user ID 0
[10/4/2016, 12:16:05 AM] [MyQ] { Devices: 
   [ { MyQDeviceId: 15261176,
       MyQDeviceTypeId: 1,
       MyQDeviceTypeName: 'Gateway',
       RegistrationDateTime: '2016-09-18T01:29:45.953',
       SerialNumber: 'GW000006AB97',
       UserName: 'iflore@gmail.com',
       UserCountryId: 0,
       Attributes: [Object],
       ChildrenMyQDeviceIds: '15261277,16648789',
       UpdatedBy: 'System',
       UpdatedDate: '2016-09-18T01:29:45.953',
       ConnectServerDeviceId: '1700389730' },
     { MyQDeviceId: 15261277,
       ParentMyQDeviceId: 15261176,
       MyQDeviceTypeId: 2,
       MyQDeviceTypeName: 'GarageDoorOpener',
       RegistrationDateTime: '2016-09-18T01:32:07.623',
       SerialNumber: 'CG083A0A0802',
       UserName: 'iflore@gmail.com',
       UserCountryId: 0,
       Attributes: [Object],
       ChildrenMyQDeviceIds: '',
       UpdatedBy: 'System',
       UpdatedDate: '2016-09-18T01:32:07.623',
       ConnectServerDeviceId: '1700389731' },
     { MyQDeviceId: 16648789,
       ParentMyQDeviceId: 15261176,
       MyQDeviceTypeId: 5,
       MyQDeviceTypeName: 'Gate',
       RegistrationDateTime: '2016-10-04T01:07:16.167',
       SerialNumber: 'CG0A6000D5B7',
       UserName: 'iflore@gmail.com',
       UserCountryId: 0,
       Attributes: [Object],
       ChildrenMyQDeviceIds: '',
       UpdatedBy: 'System',
       UpdatedDate: '2016-10-04T01:07:16.167',
       ConnectServerDeviceId: '1700861805' } ],
  ReturnCode: '0',
  ErrorMessage: '',
  CorrelationId: '196af308-fe3d-45c9-a917-805c5bfb0c27' }
[10/4/2016, 12:16:06 AM] Away for Nest02AA01AC29140FGZ is: false
[10/4/2016, 12:16:06 AM] Temperature unit for Nest02AA01AC29140FGZ is: Fahrenheit
[10/4/2016, 12:16:06 AM] Current temperature for Nest02AA01AC29140FGZ is: 23.82999
[10/4/2016, 12:16:06 AM] Current heating for Nest02AA01AC29140FGZ is: 0
[10/4/2016, 12:16:06 AM] Current humidity for Nest02AA01AC29140FGZ is: 51
[10/4/2016, 12:16:06 AM] Target heating for Nest02AA01AC29140FGZ is: 2
[10/4/2016, 12:16:06 AM] Target temperature for Nest02AA01AC29140FGZ is: 24
[10/4/2016, 12:16:06 AM] Initializing platform accessory 'Nest02AA01AC29140FGZ'...
[10/4/2016, 12:16:07 AM] [Security Panel] Request `iflore/alarmdotcom/lights/0.1.1` was unsuccessful:
 - There was an unexpected error
[10/4/2016, 12:16:07 AM] [Security Panel] Error while getting light devices: Error: Request `iflore/alarmdotcom/lights/0.1.1` was unsuccessful:
 - There was an unexpected error
[10/4/2016, 12:16:07 AM] [Security Panel] Request `iflore/alarmdotcom/locks/0.1.1` was unsuccessful:
 - There was an unexpected error
[10/4/2016, 12:16:07 AM] [Security Panel] Error while getting lock devices: Error: Request `iflore/alarmdotcom/locks/0.1.1` was unsuccessful:
 - There was an unexpected error
[10/4/2016, 12:16:07 AM] [Security Panel] Initializing platform accessory 'Alarm.com Security Panel'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 987-65-432 │     
    └────────────┘     
                       
[10/4/2016, 12:16:07 AM] Homebridge is running on port 57126.

**Comment by luisiam** [comment]
Try `sudo npm install -g git+https://github.com/luisiam/homebridge-liftmaster2.git#b8bb994805d971b478c408f0f8ba51b93022c763` and see if it works

**Comment by iflore** [comment]
Worked like a charm.  You are a genius. 

Thank you v much!!!

**Comment by luisiam** [comment]
Test all the functions and let me know if there's any problem

**Comment by iflore** [comment]
Thank you.  There is a new icon on the home app that works as expected when clicked and unclicked.  As others have reported on the boards, Siri does not recognize “Side Gate” and interprets any garage door commands as directed to both doors.  i.e. Siri processes "Open garage door” as opening both the garage door and the side gate…
