### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dxdc** [luisiam/homebridge-liftmaster2#63]
```
TypeError: Cannot read property 'length' of undefined
    at /usr/lib/node_modules/homebridge-liftmaster2/index.js:250:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Seems it's caused by this line:
```js
for (var i = 0; i < devices.length; i++) {
```

Maybe something like this, instead:

```js
if (data && data.ReturnCode === "0" && data.Devices) {
```

**Comment by sejmann** [comment]
Although necessary, I don't think that fixes the root issue, which I'm also experiencing.

Chamberlin is returning an error to LiftMaster2, but it works fine in the iOS app.  Not sure if they they require new auth, or something.

{ SecurityToken: '',
  ReturnCode: '0',
  ErrorMessage:
   'please contact customer care, supportID: 10797842851895983925',
  CorrelationId: '' }

**Comment by brbeaird** [comment]
It looks like MyQ has shut down V4 of the API. However, V5 still seems to be working, although it requires some significant code refactoring.

https://github.com/arraylabs/pymyq/issues/22#issuecomment-518861064

**Comment by dxdc** [comment]
Must have just happened today. Looks like there is a lot of V5 code here used as well, but didn't test it.

https://github.com/chanomie/homebridge-myq

**Comment by malouf-erfan** [comment]
I have the same issue as well: 

```
(node:2847) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /usr/lib/node_modules/homebridge-liftmaster2/index.js:250:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2847) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2847) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tman785** [comment]
Agree w/ @brbeaird, looks like the v4 API shut down.  

@brbeaird, I noticed you worked on some of the v5 API in pymyq....any reason why I cant use PostMan to test out v5?  It keeps failing, and it seems that I'm using your exact headers and body from the code.

**Comment by dxdc** [comment]
The V5 API works fine, but there are some changes.

I pulled the most recent headers from the iOS app. This requires `jq` to be installed. You can see the parallels with the code here (https://github.com/chanomie/homebridge-myq), which appears to be a good direction as well as `pymyq` which was previously mentioned.

```sh
#!/bin/sh
myQUsername="your@domain.com"
myQPassword="yourpassword"

myQAppId="JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu"
myQUserAgent="myQ/14041 CFNetwork/1107.1 Darwin/19.0.0"

myQToken=$( curl -s -X POST -H "Content-Type: application/json" -H "User-Agent: ${myQUserAgent}" -H "MyQApplicationId: ${myQAppId}" -d "{\"UserName\":\"${myQUsername}\",\"Password\":\"${myQPassword}\"}" "https://api.myqdevice.com/api/v5/Login" | jq -r '.SecurityToken' )

if [ -z "${myQToken}" ]; then
  echo "Problem fetching security token"
  exit 1
fi

echo "Security token: ${myQToken}"

myqAccountId=$( curl -s -G -H "User-Agent: ${myQUserAgent}" -H "MyQApplicationId: ${myQAppId}" -H "SecurityToken: ${myQToken}" "https://api.myqdevice.com/api/v5/Accounts" | jq -r '.Items[0].Id' )

echo "Account Id (first only): ${myqAccountId}"

curl -s -H "User-Agent: ${myQUserAgent}" -H "MyQApplicationId: ${myQAppId}" -H "SecurityToken: ${myQToken}" "https://api.myqdevice.com/api/v5.1/Accounts/${myqAccountId}/Devices" | jq '.'

# This works to show a list of devices
```

**Comment by tman785** [comment]
I see what I did wrong....I have it working.  Thanks!

**Comment by yetdog** [comment]
Funny - even my iOS app appears to not work. I can sign in OK, my openers show up, but when I tap the button to open, it says Opening..., my door does nothing, and then the icon goes back to Closed.

**Comment by brbeaird** [comment]
Anyone have any idea how to turn lamp modules on and off in the V5 API?

**Comment by brbeaird** [comment]
@dxdc - I've not heard about jq. I'd love to be able to view the iOS app payload (specifically to figure out what the new command is for the lamp module. Is there any documentation out there that shows more about how to do that?

**Comment by sejmann** [comment]
Oh, jq is a very handy command line tool to parse, query, modify and create json using a compact query language, like xpath but for json.  I use it frequently in shell scripts, as @dxdc had. Obviously it's not needed from within js, but it's nice for a quick and dirty REST api client from a shell script, coupled with curl. =)

**Comment by dxdc** [comment]
@sejmann's explanation is spot on. 

@brbeaird The latest app uses SSL pinning, so you won't be able to easily work around it that way (using Charles for example). You could look into apktool and the Android variant too.

**Comment by vlaryn** [comment]
Sorry for the noob question here but how do I get my homebridge install to pull the latest version with all the latest merges. When I run the npm list -g it shows my lift master2 is version 0.5.0. When I run the sudo npm install -g --unsafe-perm homebridge-liftmaster2@latest it says its already up to date. 
Thanks 
Wayne B.

**Comment by lsmith07** [comment]
Has anyone determined a solution or workaround to get this plug-in working again?  I apologize if I missed it above.  I’m curious what those of you who commented previously have done:  live with “unresponsive” in homekit for all homebridge accessories, remove liftmaster2 from the config.json file, replace plug-in with another, or update code somewhere.  I’m considering installing the chamberlain plug-in and modifying the api.js file, but would prefer not to.

**Comment by pponce** [comment]
Remove liftmaster2 via the removal instructions in it's readme.
Replace with https://github.com/hjdhjd/homebridge-myq2

**Comment by lsmith07** [comment]
Thank you for the response @pponce.  I’m back in business with myq2 installed!

**Comment by wmparsons** [comment]
Is anyone actively working on migrating to the v5 API? I can help but will need some help on how to debug a plugin.  I've got node experience, but will be my first time making changes to a homebridge plugin.

**Comment by chowielin** [comment]
https://github.com/hjdhjd/homebridge-myq2 works for me too. Thank you! @pponce 
Note to others, change your config json from username to email. The platform name has changed as well.
